export const sliderData = [
  {
    icon: "/assets/img/slider_btc_img.png",
    name: "BTC",
    amount: 721882,
    desc: "Bitcoin",
    range: -4.66,
    graphImg: "/assets/img/slider_img_1.png",
  },
  {
    icon: "/assets/img/slider_btc_img.png",
    name: "BTC",
    amount: 721882,
    desc: "Bitcoin",
    range: -4.66,
    graphImg: "/assets/img/slider_img_1.png",
  },
  {
    icon: "/assets/img/slider_btc_img.png",
    name: "BTC",
    amount: 721882,
    desc: "Bitcoin",
    range: -4.66,
    graphImg: "/assets/img/slider_img_1.png",
  },
  {
    icon: "/assets/img/slider_btc_img.png",
    name: "BTC",
    amount: 721882,
    desc: "Bitcoin",
    range: -4.66,
    graphImg: "/assets/img/slider_img_1.png",
  },
  {
    icon: "/assets/img/slider_btc_img.png",
    name: "BTC",
    amount: 721882,
    desc: "Bitcoin",
    range: -4.66,
    graphImg: "/assets/img/slider_img_1.png",
  },
];
